[package]
name = "aprilasr"
version = "0.2.0"
authors = ["VHS <vhsdev@tutanota.com>"]
edition = "2021"

include = [
    "/examples",
    "/src",
    "CHANGELOG.md",
    "COPYING",
    "README.md",
    "getmodel.sh",
    "makewav.sh",
]

description = "High-level wrapper for the april-asr C api (libaprilasr) using aprilasr-sys."
repository = "https://codeberg.org/vhs/aprilasr-rs"
keywords = ["nlp", "ffi", "speech-recognition", "audio", "asr"]
categories = ["external-ffi-bindings", "multimedia", "text-processing"]
license = "GPL-3.0-or-later"
readme = "README.md"

[dependencies]
aprilasr-sys = "0.1.4"

[dev-dependencies]
md5 = "0.7.0"
